---
- name: Deploy Matrix stack with Podman
  hosts: all
  gather_facts: false
  vars:
    synapse_image: docker.io/matrixdotorg/synapse:latest
    postgres_image: docker.io/library/postgres:16-alpine
    coturn_image: docker.io/instrumentisto/coturn:latest
    element_web_image: docker.io/vectorim/element-web:latest
    element_call_image: docker.io/elementcall/element-call:latest
    keycloak_image: docker.io/bitnami/keycloak:latest
    nginx_image: docker.io/library/nginx:latest
  tasks:
    - name: Ensure Podman is installed
      ansible.builtin.package:
        name: podman
        state: present

    - name: Run PostgreSQL container
      containers.podman.podman_container:
        name: postgres
        image: "{{ postgres_image }}"
        state: started
        env:
          POSTGRES_PASSWORD: synapse
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
      when: not ansible_check_mode


    - name: Run Synapse container
      containers.podman.podman_container:
        name: synapse
        image: "{{ synapse_image }}"
        state: started
        env:
          SYNAPSE_SERVER_NAME: "{{ inventory_hostname }}"
          SYNAPSE_REPORT_STATS: "no"
        ports:
          - "8008:8008"
        volumes:
          - synapse_data:/data
      when: not ansible_check_mode

    - name: Run Coturn container
      containers.podman.podman_container:
        name: coturn
        image: "{{ coturn_image }}"
        state: started
        ports:
          - "3478:3478/udp"
      when: not ansible_check_mode

    - name: Run Element Web container
      containers.podman.podman_container:
        name: element-web
        image: "{{ element_web_image }}"
        state: started
        ports:
          - "8080:80"
      when: not ansible_check_mode

    - name: Run Element Call container
      containers.podman.podman_container:
        name: element-call
        image: "{{ element_call_image }}"
        state: started
        ports:
          - "5082:80"
      when: not ansible_check_mode

    - name: Run Keycloak container
      containers.podman.podman_container:
        name: keycloak
        image: "{{ keycloak_image }}"
        state: started
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
          - "8081:8080"
      when: not ansible_check_mode

    - name: Create Nginx configuration
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/nginx.conf"
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:8080;
              }
              location /call/ {
                  proxy_pass http://localhost:5082/;
              }
              location /synapse/ {
                  proxy_pass http://localhost:8008/;
              }
              location /keycloak/ {
                  proxy_pass http://localhost:8081/;
              }
          }
      when: not ansible_check_mode

    - name: Run Nginx container
      containers.podman.podman_container:
        name: nginx
        image: "{{ nginx_image }}"
        state: started
        ports:
          - "80:80"
        volumes:
          - "{{ ansible_env.HOME }}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      when: not ansible_check_mode
