name: Ansible CI

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==2.18.* ansible-lint
      - name: Install Galaxy requirements
        run: ansible-galaxy collection install -r requirements.yml
      - name: ansible-lint
        run: ansible-lint deploymatrix.yml
      - name: syntax-check
        run: ansible-playbook --syntax-check -i inventory/hosts deploymatrix.yml
